POST https://d6385864ee9d389e10574b8ab7c6a688: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@ridgecrest-herbals.myshopify.com/admin/api/2021-10/orders/4587269456068/refunds.json
X-Shopify-Access-Token: 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
Content-Type: application/json

{"refund":{
    "currency":"USD",
    "note": "Testing the reason",
  "shipping":{"full_refund":"true"},
  "refund_line_items":[],
    "transactions":[{"parent_id":5607372619972,"amount":"7","kind":"refund","gateway":"shopify_payments"}]}}